version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "campus-l3-dev-stack-test-maelys"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9eb3wbkgn64o"
s3_prefix = "campus-l3-dev-stack-test-maelys"
region = "eu-west-2"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "AppName=\"campus-l3-dev-app-maelys\" Stage=\"dev\""
image_repositories = []
confirm_changeset = true
