AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  AppName:
    Type: String
    Default: campus-app
Stage:
    Type: String
    Default: dev

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowMethods: "'POST, GET, OPTIONS, PUT'"
        AllowHeaders: "'Accept, Content-Type, Content-Length, Authorization, X-Api-Key'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
    Name:
      Fn::Sub: ${AppName}-api-${Stage}
    StageName: !Ref Stage
    DefinitionBody:
      Fn::Transform:
        Name: AWS::Include
        Parameters:
          Location: specification/OpenApi.yml

  GetDevices:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      Runtime: python3.8
      PackageType: Zip
      FunctionName:
        Fn::Sub: ${AppName}-get-devices-${Stage}
      Description: Get the list of devices
      CodeUri: ./src/devices
      Handler: handler.get_devices
    


